#!/usr/bin/env bash
set -euo pipefail

INTERNAL="eDP-1"
# you could also use jq and use actual_dp here for in case the connection does not work perfect
EXTERNAL="$(xrandr | awk '/ connected/ && $1 != "'"$INTERNAL"'" {print $1; exit}' || true)"

if [[ -z "$EXTERNAL" ]]; then
	# mobile geometry
	safenotify.sh "DISPLAY CONNECTION: switching display to mobile" 
	
	# disabling the other connected and disconnected displays
	for out in $(xrandr | awk '/ connected| disconnected/ {print $1}'); do
	    [[ "$out" != "$INTERNAL" ]] && xrandr --output "$out" --off
	done
	    xrandr --output "$INTERNAL" --auto --primary
	    for i in {1..9}; do
		i3-msg "workspace $i; move workspace to output $INTERNAL" >/dev/null
	done
	xrandr --output "$INTERNAL" --auto --primary --pos 0x0
	xrandr --fb 1920x1200

else
	actual_dp=$(i3-msg -t get_outputs | jq -r '.[] | select(.active == true and .name != "eDP-1") | .name')

safenotify.sh "DISPLAY CONNECTION: switching display to EXTERNAL = $EXTERNAL" 
    # docked geometry
    xrandr --output "$EXTERNAL" --auto --above "$INTERNAL"
    xrandr --output "$INTERNAL" --auto --primary
    for i in {1..8}; do
        i3-msg "workspace $i; move workspace to output $actual_dp" >/dev/null
    done
    i3-msg "workspace 9; move workspace to output $INTERNAL" >/dev/null
fi

