# Luke's config for the Zoomer Shell
source ~/.config/shell/common.sh
# source some extra functions that i've made
source ~/.config/zsh/zshrc-extra.zsh


# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.


### making the man pages readable
export LESS='-R --tabs=4'
export MANPAGER='less -R --tabs=4'

### getting zoxide to work
eval "$(zoxide init zsh)"
# fzf integration for zsh (fzf >= 0.48.0)
source <(fzf --zsh)

# vi mode
bindkey -v
export KEYTIMEOUT=20

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char
# use the alt . to put old words back
bindkey -M viins '^[.' insert-last-word


# Change cursor shape for different vi modes.
function zle-keymap-select {
  case $KEYMAP in
    vicmd)
      echo -ne '\e[1 q'   # block
      ;;
    viins|main)
      echo -ne '\e[5 q'   # beam
      ;;
  esac
}
zle -N zle-keymap-select
zle-line-init() {
  zle -K viins
}
zle -N zle-line-init

# Use lf to switch directories and bind it to ctrl-o
# lfcd () {
#     tmp="$(mktemp)"
#     lf -last-dir-path="$tmp" "$@"
#     if [ -f "$tmp" ]; then
#         dir="$(cat "$tmp")"
#         rm -f "$tmp"
#         [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
#     fi
# }
# bindkey -s '^o' 'lfcd\n'

# Edit line in vim with ctrl-e: ADD this when you want to get it to work (when other stuff starts working)
#autoload edit-command-line; zle -N edit-command-line
#bindkey '^e' edit-command-line

# Load aliases and shortcuts if existent.
# [ -f "$HOME/.config/shortcutrc" ] && source "$HOME/.config/shortcutrc"
# [ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"

# Load zsh-syntax-highlighting; should be last.
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
print "ZSHRC LOADED"
